title: Test Project's content
baseurl: "/TestProject"

tipue_search:
  include:
    pages: true
  exclude:
    files: [Description3.md]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-html-pipeline

header_pages:
  - search.html
    
theme: minima
