title: Test Project's content
baseurl: "/TestProject"

tipue_search:
  include:
    pages: true
  exclude:
    files: [Description3.md]

header_pages:
  - content.md
  - search.html
  - apiIndex.html
    
theme: minima
